#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 19 10:22:17 2019

@author: artun
"""

from collections import namedtuple

import sys
import docplex.mp
from docplex.mp.model import Model

from docplex.mp.model import Model
from docplex.util.environment import get_environment
url = None
key = None         
cost = [('cost_gunduz',3),
       ('cost_aksam',5)]

call_goal =     [( 600),
            ( 480),
            ( 400),
            ( 440)]

call_ratio =    [( 0.3, 0.3),
            ( 0.1, 0.3),
            (0.1, 0.15),
            (0.1, 0.20)]

m = Model(name='call_center')
products = [('morning'),('evening')]
lengh = len(call_goal)
lengh2 = len(call_ratio[0])

evening = m.integer_var(name='evening')
morning = m.integer_var(name='morning')
# call number constraint
#x= [[call_goal[call]*(call_ratio[call][i]) for i in range(lengh2)] for call in range(lengh)]
#x= [[call_goal[call]*(call_ratio[call][i]) for i in range(lengh2)] for call in range(lengh)]
#[[m.sum([call_goal[call]*(call_ratio[call][i]) for i in range(lengh2)])>=call_goal[call] for call in range(lengh)]
#m.add_constraints(m.sum(call_goal[call]*(call_ratio[call][i]) for i in range(lengh2))>=call_goal[call] for call in range(lengh))

m.add_constraints((morning * call_ratio[i][0] + evening * call_ratio[i][1] >= call_goal[i]) for i in range(lengh))
m.add_constraint(evening <= 0.4*evening+0.4*morning)

m.minimize(3*morning+5*evening)
s = m.solve(url=url, key=key)
m.print_solution()
m.print_information()
